# AI-Enhanced PDF Extraction System
# Docker Compose mit Ollama Integration

version: '3.8'

services:
  # Ollama AI Service (lokale LLM/Vision Models)
  ollama:
    image: ollama/ollama:latest
    container_name: pdf-extractor-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    networks:
      - pdf-extractor-network

  # PDF Extraction System
  pdf-extractor:
    build: .
    container_name: pdf-extractor-app
    volumes:
      - ./Documents:/app/Documents
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - pdf-extractor-network

volumes:
  ollama_data:
    driver: local

networks:
  pdf-extractor-network:
    driver: bridge
